import type { Strings } from "@/types";

export const STRINGS: Record<string, Strings> = {
  en: {
    appName: "Varalaru",
    tagline: "The History of Tamil People",
    nav: { leaders: "Leaders", works: "Works" },
    section: {
      leaders: { title: "Leaders", desc: "People who shaped Tamil history - kings, poets, freedom fighters and statesmen." },
      works:   { title: "Works",   desc: "Poems, Thirukkural couplets, verses and attributed words from Tamil leaders and poets." },
    },
    search: "Search by name, category, or tag...",
    searchWorks: "Search works by text or author...",
    leadersCount: (n) => `${n} ${n === 1 ? "leader" : "leaders"}`,
    worksCount:   (n) => `${n} ${n === 1 ? "work" : "works"}`,
    pageOf: (p, t) => `page ${p} of ${t}`,
    viewWorks: (n) => `${n} ${n === 1 ? "work" : "works"} →`,
    biography: "Biography",
    highlights: "Highlights",
    relatedFigures: "Related Figures",
    tags: "Tags",
    notYet: "· not yet added",
    light: "Light",
    dark: "Dark",
    noResults: (q) => `No results for "${q}"`,
    present: "present",
    requestLeader: "Request a Leader",
    requestDesc: "Can't find someone? Let us know.",
    requestBtn: "Submit Request →",
    shareCard: "Share",
    download: "Download",
    copyLink: "Copy Link",
    copied: "Copied!",
    leaderCard: "Leader Card",
    workCard: "Work Card",
    by: "- ",
    workTypeLabel: { quote: "Quote", poem: "Poem", kural: "Thirukkural" },
    kuralNumber: (n) => `Kural ${n}`,
    allWorks: "All works",
    backToAll: "← All leaders",
    readMoreButton: "Read More"
  },
  ta: {
    appName: "வரலாறு",
    tagline: "வரலாறு",
    nav: { leaders: "தலைவர்கள்", works: "ஆக்கங்கள்" },
    section: {
      leaders: { title: "தலைவர்கள்",  desc: "தமிழ் வரலாற்றை வடிவமைத்தவர்கள் - மன்னர்கள், கவிஞர்கள், விடுதலை தலைவர்கள் மற்றும் அரசியல்வாதிகள்." },
      works:   { title: "ஆக்கங்கள்", desc: "தமிழ் தலைவர்கள் மற்றும் கவிஞர்களின் கவிதைகள், திருக்குறள் குறட்பாக்கள், பாடல்கள் மற்றும் மேற்கோள்கள்." },
    },
    search: "பெயர், வகை அல்லது குறிச்சொல் மூலம் தேடுக...",
    searchWorks: "ஆக்கங்களை உரை அல்லது ஆசிரியர் மூலம் தேடுக...",
    leadersCount: (n) => `${n} தலைவர்${n === 1 ? "" : "கள்"}`,
    worksCount:   (n) => `${n} ஆக்கம்${n === 1 ? "" : "கள்"}`,
    pageOf: (p, t) => `பக்கம் ${p} / ${t}`,
    viewWorks: (n) => `${n} ஆக்கம்${n === 1 ? "" : "கள்"} →`,
    biography: "வாழ்க்கை வரலாறு",
    highlights: "முக்கிய நிகழ்வுகள்",
    relatedFigures: "தொடர்புடைய நபர்கள்",
    tags: "குறிச்சொற்கள்",
    notYet: "· இன்னும் சேர்க்கப்படவில்லை",
    light: "வெளிர்",
    dark: "இருள்",
    noResults: (q) => `"${q}" க்கான முடிவுகள் இல்லை`,
    present: "இன்றும் உயிரோடு",
    requestLeader: "தலைவரை கோருங்கள்",
    requestDesc: "யாரையாவது காணவில்லையா? எங்களிடம் தெரிவியுங்கள்.",
    requestBtn: "கோரிக்கை அனுப்பு →",
    shareCard: "பகிர்",
    download: "பதிவிறக்கு",
    copyLink: "இணைப்பை நகலெடு",
    copied: "நகலெடுக்கப்பட்டது!",
    leaderCard: "தலைவர் அட்டை",
    workCard: "ஆக்க அட்டை",
    by: "- ",
    workTypeLabel: { quote: "மேற்கோள்", poem: "கவிதை", kural: "திருக்குறள்" },
    kuralNumber: (n) => `குறள் ${n}`,
    allWorks: "அனைத்து ஆக்கங்கள்",
    backToAll: "← அனைத்து தலைவர்கள்",
    readMoreButton: "மேலும் படிக்க"
  },
};
